# 행렬의 분류 (이론)
## Matrix 분류와 적합한 Inverse 알고리즘

- Real Matrix
    - Symmetric
        - Positive definite
        - Negative definite
        - Indefinite
    - Non-symmetric

- Complex Matrix
    - Hermitian: $A = {A}^*$ (\*: Transpose and Conjugate)
    - Non-Hermitian
    
- Positive definite이면 
    - Cholesky decomposition ($A = {R}^TR = L{L}^T, A = {R}^*R = L{L}^*$)
    - LDL decomposition ($A = UD{U}^T = LD{L}^T, A = UD{U}^* = LD{L}^*$)
    - LU decomposition

- Positive definite인지 모를 때
    - Diagonal pivoting method
        - $A = UD{U}^T = LD{L}^T$: block symmetric diagonal
        - $A = UD{U}^* = LD{L}^*$: block Hermitian diagonal
        
        
### Complex symmtric matrix (Hermitian과는 다름)
- boundary integral equations 분야에서 사용
- Diagonal pivoting method: $A = UD{U}^T = LD{L}^T$: block symmtric diagonal 사용


### Matrix의 모양으로 분류
- Full Matrix: $A = \begin{bmatrix}
                    {a}_{11} & {a}_{12} & {a}_{13} & \dots & {a}_{1n} \\
                    {a}_{21} & {a}_{22} & {a}_{23} & \, & \, \\
                    {a}_{31} & {a}_{32} & {a}_{33} & \, & \, \\
                    \vdots & \, & \, & \ddots & \, \\
                    {a}_{n1} & \, & \, & \, & {a}_{nn} \\
                    \end{bmatrix}$
                    
- Band Matrix: $A = \begin{bmatrix}
                    {a}_{11} & {a}_{12} & {a}_{13} & 0 & 0 \\
                    {a}_{21} & {a}_{22} & {a}_{23} & {a}_{24} & 0 \\
                    0 & {a}_{32} & {a}_{33} & {a}_{34} & {a}_{35} \\
                    0 & 0 & {a}_{43} & {a}_{44} & {a}_{45} \\
                    0 & 0 & 0 & {a}_{54} & {a}_{55} \\
                    \end{bmatrix}$
    - 0 이 많아 저장용량의 낭비, Band Matrix로 변환 $\to$ $\begin{bmatrix}
                    0 & 0 & {a}_{13} & {a}_{24} & {a}_{35} \\
                    0 & {a}_{12} & {a}_{23} & {a}_{34} & {a}_{45} \\
                    {a}_{11} & {a}_{22} & {a}_{33} & {a}_{44} & {a}_{55} \\
                    {a}_{21} & {a}_{32} & {a}_{43} & {a}_{54} & 0 \\
                    \end{bmatrix}$ or  $\begin{bmatrix}
                    0 & {a}_{11} & {a}_{12} & {a}_{13} \\
                    {a}_{21} & {a}_{22} & {a}_{23} & {a}_{24} \\
                    {a}_{32} & {a}_{33} & {a}_{34} & {a}_{35} \\
                    {a}_{43} & {a}_{44} & {a}_{45} & 0 \\
                    {a}_{54} & {a}_{55} & 0 & 0 \\
                    \end{bmatrix}$ 
                    
### 특별한 Matrix
- Toeplitz matrix: $\begin{bmatrix}
                    {a}_{0} & {a}_{-1} & {a}_{-2} & \dots & \dots & {a}_{-(n-1)} \\
                    {a}_{1} & {a}_{0} & {a}_{-1} & \ddots & \, & \vdots \\
                    {a}_{2} & {a}_{1} & \ddots & \ddots & \ddots & \vdots \\
                    \vdots & \ddots & \ddots & \ddots & {a}_{-1} & {a}_{-2}\\
                    \vdots & \, & \ddots & a_{1} & {a}_{0} & {a}_{-1}\\
                    {a}_{n-1} & \dots & \dots & {a}_2 & {a}_1 & {a}_0 \\
                    \end{bmatrix}$
                    
- Circulant Matrix: $\begin{bmatrix}
                    {c}_{0} & {c}_{n-1} & \dots & {c}_2 & {c}_1 \\
                    {c}_{1} & {c}_{0} & {c}_{n-1} & \, & {c}_2 \\
                    \vdots & {c}_{1} & {c}_0 & \ddots & \vdots \\
                    {c}_{n-2} & \, & \ddots & \ddots & {c}_{n-1} \\
                    {c}_{n-1} & {c}_{n-2} & \dots & {c}_1 & {c}_{0} \\
                    \end{bmatrix}$

# 왜 역행렬을 구하는 것보다 $Ax = b$를 푸는게 좋을까?
- 컴퓨터를 통해 $Ax = b$의 해를 구하는 방법
    - 1. ${A}^{-1}$을 구해 해를 찾는 경우
    - 2. $Ax = b$를 풀어 해를 찾는 경우
    
- 컴퓨터에서는 수를 제한된 소수점으로 표현, 수치적 정확도 때문에 $Ax = b$를 푸는 경우가 더 좋다.
 
 
### 희소 행렬(Sparse Matrix)의 역행렬과 LU Decomposition 비교
- 행렬이 Sparse하면 그 역행렬은 대부분 dense하다. 반면 L과 U는 여전히 Sparse한 경우가 많다.

### 결론: 특별히 ${A}^{-1}$이 필요한 경우가 아니라면, $Ax = b$를 풀때 역행렬을 구하지 말자!

# 행렬 방정식

In [1]:
import numpy as np
from scipy import linalg

## Determinant 구하기
- linalg.det
- 내부 기본 알고리즘: LU decomposition (A = LU)
    - 해당 Lapack 함수(subroutine): zgetrf(complex128) , dgetrf(float64)

In [2]:
A1 = np.array([[1,5,0], [2,4,-1], [0,-2,0]])
det_A1 = linalg.det(A1)
A2 = np.array([[1,-4,2], [-2,8,-9], [-1,7,0]])
det_A2 = linalg.det(A2)
det_A1, det_A2

(-2.0, 15.0)

## 역행렬 구하기
- linalg.inv
- $Ax = b$를 푸는 것이라면, 역행렬이 필요한지 반드시 다시 한번 생각을 해보기
- 역행렬이 존재하지 않는다면 singular matrix라고 에러 발생
- 기본 알고리즘: LU decomposition, solve $LU{A}^{-1} = I$
- Lapack: getrf (LU decomposition), getri (inverse from triangular matrix)

In [3]:
A = np.array([[1,2,1], [2,1,3], [1,3,1]])
inv_A = linalg.inv(A)
inv_A

array([[ 8., -1., -5.],
       [-1.,  0.,  1.],
       [-5.,  1.,  3.]])

## Ax = b 풀기
- linalg.solve(A, b, assume_a = "")
    - assume_a option: "gen", "sym", "her", "pos"
        - "gen": 행렬의 특성을 모르겠다.
            - LU decomposition (A = LU) - Lapack: gesv
        - "sym": symmetric matrix ($A = {A}^T$), complex symmetric(**NOT Hermitian)
            - diagonal pivoting ($A = LD{L}^T$) -Lapack: sysv 
            
        - "her": Hermitian matrix ($A = {A}^*$)
            - diagonal pivoting ($A = LD{L}^*$) - Lapack: hesv
        - "pos": positive definite, ${x}^{T}Ax > 0$, symmetric/Hermitian
            - Cholesky decomposition ($A = {R}^TR = L{L}^T$) - Lapack: posv

- assume_a의 옵션을 잘못 설정하더라도 별다른 오류 표시 없이 문제를 푼다. 잘못된 답일 수 도 있으니 주의! 특성을 모르면 그냥 "gen"을 사용하자!

## Triangular matrix solver
- $Ax = b$, $A$ = upper triangular matrix, lower triangular matrix
- x = linalg.solve_triangular(A, b, lower=False) - Lapack: trtrs

In [6]:
A = np.array([[1,0,0,0], [1,4,0,0], [5,0,1,0], [8,1,-2,2]])
b = np.array([1,2,3,4])
x = linalg.solve_triangular(A, b, lower=True)
x

array([ 1.   ,  0.25 , -2.   , -4.125])

## 구한 해가 정확한가 검증
- $Ax = b$, x: 수치적 계산으로 근사된 값
- Ax, b 충분히 비슷한가?, Ax - b 충분히 작은가? 0에 충분히 가까운가?
- np.allclose()
- np.allclose(A@x, b)
- np.allclose(A@x - b, np.zeros((b.shape[0],)))

In [8]:
A = np.array([[2,-1,0], [-1,2,-1], [0,-1,2]])
b = np.array([1,1,1])
x = linalg.solve(A, b, assume_a = "pos")
zr = np.zeros((3,))
bool_close = np.allclose(A@x-b, zr)
bool_close

True

In [20]:
# 연습 문제
## Practice 1.
A = linalg.hilbert(10)
inv_A = linalg.inv(A)
b = np.ones((10,))
x1 = inv_A@b
x2 = linalg.solve(A, b, assume_a="gen")

bool_close = np.allclose(x1, x2)
bool_close

True

# 밴드 행렬

## Scipy에서 밴드 행렬 입력

- 열(column) index를 유지하면서 밴드만 가져와서 가로 형태로 쌓아줌

## 밴드 행렬 Solver
- $Ax = b$, A: 밴드 행렬이 유리! (공간 절약, 연산 시간 절약)
- linalg.solve_banded
- linalg.solve_banded((lbw, ubw), band_a, b)
    - 기본 알고리즘: 
        - 1. LU decomposition - Lapack: gbsv
        - 2. tridiagonal solver - Lapack: gtsv
    

In [25]:
A = np.array([[1,2,0,0,0],[1,4,1,0,0],[5,0,1,2,0],[0,1,2,2,1],[0,0,2,1,1]])
band_A = np.array([[0,2,1,2,1],[1,4,1,2,1],[1,0,2,1,0],[5,1,2,0,0]])
b = np.ones((5,))
x = linalg.solve_banded((2,1), band_A, b)
x

array([ 0.42857143,  0.28571429, -0.57142857, -0.28571429,  2.42857143])

## 밴드 행렬의 Solver의 Solution 확인은 어떻게?
band_A @ x $\neq$ b, A@x = b
- band 행렬을 다시 원래의 행렬로 돌려놓고 matrix-vector multiplication 하는 것은 본래의 목적에서 벗어남
$\to$ 강의에서 제공하는 custom function을 사용

## Positive Definite 행렬의 밴드 행렬 Solver
- Positive definite: Symmetric / Hermitian
- linalg.solveh_banded
- x = linalg.solveh_banded(band_a_h, b, lower=False)
- 기본 알고리즘:
    - 1. Cholesky decomposition - Lapack: pbsv
    - 2. $LD{L}^T$ decomposition - Lapack: ptsv

In [48]:
# 연습 문제
## Practice 1.
diag_A = 2*np.ones((10000,))
zero_vec = np.zeros((1,))
one_vec = np.ones((9999,))
b = np.ones((10000,))

first_band = np.hstack((zero_vec, one_vec))
minus1_band = np.hstack((one_vec, zero_vec))
band_A = np.vstack((first_band, diag_A))
band_A = np.vstack((band_A, minus1_band))
band_A

array([[0., 1., 1., ..., 1., 1., 1.],
       [2., 2., 2., ..., 2., 2., 2.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [52]:
x = linalg.solve_banded((1,1), band_A, b)
x

array([4.99950005e-01, 9.99900010e-05, 4.99850015e-01, ...,
       4.99850015e-01, 9.99900010e-05, 4.99950005e-01])

# 특수 행렬
## Toeplitz 행렬 Solver
- linalg.solve_toeplitz(c,r), b) (c: 1st column of matrix, r: 1st row of matrix)
- 알고리즘: Levison-Durbin recursion

In [55]:
T = np.array([[1,-1,-2,-3], [3,1,-1,-2], [6,3,1,-1], [10,6,3,1]])
c = T[:,0]
r = T[0,:]
b = np.array([1,1,1,1])
x = linalg.solve_toeplitz((c,r), b)
x

array([ 1.66666667e-01, -5.27355937e-16, -1.66666667e-01, -1.66666667e-01])

## Toeplitz Matrix 구축
- linalg.toeplitz
- toeplitz_full_matrix = linalg.toeplitz(c,r)

## Circulant 행렬 Solver
- linalg.solve_circulant
- x = linalg.solve_circulant(c, b) (c: 1st column of matrix)

## Circulant Matrix 구축
- linalg.circulant
- circulant_full_matrix = linalg.circulant(c)

# 여러 식을 한꺼번에 풀기
위에서 사용한 모든 module들에 두번에 b(vector)에 해당하는 값에 B(matrix)사용하면 된다.
- 일반 행렬
    - x = linalg.solve(A, B, assume_a = "gen")
    - x = linalg.solve_triangular(A, B, lower=False)
- 밴드 행렬
    - x = linalg.solve_banded((lbw, ubw), band_a, B)
    - x = linalg.solve_bnaded(band_a_h, B, lower=False)
- 특수 행렬
    - x = linalg.solve_toeplitz((c,r), B)
    - x = linalg.solve_circulant(c, B)
    
### b (vector)를 바꿔가면서 여러번 풀면 되는 것이 아닌가?
b를 바꿔가며 반복하면 계속 쓸데없이 내부에서 decomposition을 하면서 계산 시간을 낭비함