# Eigenvalue(고유치) 계산 알고리즘 개론

### 보통 사용하는 Algorithm: QR Algorithm

### 컴퓨터로 어떻게 QR Decomposition을 하나?
- 선형대수학 강좌: Gram-Schmidt Process
- Givens reduction(Jacobi 변형)
- **Householder method**

#### QR Decomposition by Householder Method
$A = \begin{bmatrix}
      x & x & x \\
      x & x & x \\
      x & x & x \\
      x & x & x \\
      x & x & x \\
      \end{bmatrix}$ ${P}_1 \to$ ${P}_1A = \begin{bmatrix}
      x & x & x \\
      0 & x & x \\
      0 & x & x \\
      0 & x & x \\
      0 & x & x \\
      \end{bmatrix}$ ${P}_2 \to$ ${P}_2{P}_1A = \begin{bmatrix}
      x & x & x \\
      0 & x & x \\
      0 & 0 & x \\
      0 & 0 & x \\
      0 & 0 & x \\
      \end{bmatrix}$ ${P}_3 \to$ ${P}_3{P}_2{P}_1A = \begin{bmatrix}
      x & x & x \\
      0 & x & x \\
      0 & 0 & x \\
      0 & 0 & 0 \\
      0 & 0 & 0 \\
      \end{bmatrix}$
- $Q = {P}_1{P}_2{P}_3$, ${P}_1, {P}_2, \dots$: **Householder reflector(matrix)**

#### Householder Reflector for QR Decomposition
- $P = I - 2u{u}^T$
- $Px = \alpha {e}_1$

#### QR Algorithm 구분
- One step: 기본 알고리즘을 그대로 사용, 시간이 많이 걸려서 one step 방법을 사용하지는 않는다.
- Two step: 
    - a) symmetric(Hermitian) matrix: all eigenvalues are real
        - 1) Reduction to tridiagonal matrix: Householder
        - 2) QR algorithm: QR decomposition per iteration + shift method
    - b) non-symmetric matrix
        - 1) Balancing: reduces matrix Euclidean norm
        - 2) Reduction to upper Hessenberg matrix: Householder
        - 3) QR algorithmL QR decomposition per iteration + shift method
       
### Hessenberg Form by Householder Reduction
- $ A = {Q}_1{R}_1, {A}_1 = {R}_1{Q}_1$, 
- ${A}_1 = {Q}_2{R}_2, {A}_2 = {R}_2{Q}_2 \dots$
- 무한히 반복이 진행되면 ${A}_k$는 다음과 같은 형태로 수렴: $\begin{bmatrix}
                                                          {\lambda}_1 & \, & \, & \,& \,& \,& \, \\
                                                          0 & {\lambda}_2 & \,& \,& \,& \,& \, \\
                                                          \, & \, & \ddots & \,& \,& \,& \, \\
                                                          \, & \, & \, & \, & {d}_r & {u}_r & \, \\
                                                          \, & \, & \, & \, & {l}_{r+1} & {d}_{r+1} & \, \\
                                                          \, & \, & \, & \, & \, & \ddots & \ddots \\
                                                          \, & \, & \, & \, & \, & \, & {\lambda}_n \\
                                                          \end{bmatrix}$
- 2 x 2 block의 characteristic equations의 solution이 eigenvalues

# 고유치 계산
## 일반 행렬
### 일반 행렬의 Eigenvalue & Eigenvector
- linalg.eig
- eigvals, eigenvecs = linalg.eig(A, M) (M:option, eigvals: 1D array(vector), eigenvecs: 2D array(matrix))

### 일반 행렬의 Eigenvalue만 구하기
행렬 A와 eigenvector 행렬의 사이즈는 동일, eigenvector 계산을 안하면 계산 부담도 줄어듬
- eigvals = linalg.eig(A, M, right=False)

### Symmetric or Hermitian 행렬의 Eigenvalue / Eigenvector
- linalg.eigh
- eigvals, eigenvecs = linalg.eigh(A, M)

### Symmetric or Heritian 행렬의 Eigenvalue만 구하기
- eigvals = linalg.eigh(A, M, eigvals_only = True)

In [2]:
import numpy as np
from scipy import linalg
import timeit

In [3]:
A = np.array([[6,3,1,5], [3,0,5,1], [1,5,6,2], [5,1,2,2]])

start = timeit.default_timer()
eigvals, eigvec = linalg.eigh(A)
end = timeit.default_timer()

eigvals, eigvec , end - start


(array([-3.74637491, -0.76263923,  6.08502336, 12.42399079]),
 array([[-0.35986577,  0.40700525,  0.58177024, -0.60529888],
        [ 0.76481823,  0.44157496, -0.24929195, -0.39738916],
        [-0.42255936, -0.15465567, -0.7128596 , -0.53791859],
        [ 0.32709828, -0.78449978,  0.3020399 , -0.43166968]]),
 0.02239142102189362)

In [4]:
# 연습 문제 
## Practice 1.
A = np.diag(2*np.ones((1000,))) + np.diag(np.ones((999,)), k=1) + np.diag(np.ones((998,)), k=2) + np.diag(np.ones((999,)), k=-1) + np.diag(np.ones((998,)), k=-2)

start = timeit.default_timer()
eigvals, eigvecs = linalg.eigh(A)
end = timeit.default_timer()

print("computing time: ", end - start, "eigval: ", eigvals, "eigvecs: ", eigvecs)


computing time:  0.12470249400939792 eigval:  [-2.49963209e-01 -2.49963064e-01 -2.49852839e-01 -2.49852257e-01
 -2.49668894e-01 -2.49667586e-01 -2.49411379e-01 -2.49409062e-01
 -2.49080306e-01 -2.49076699e-01 -2.48675686e-01 -2.48670517e-01
 -2.48197533e-01 -2.48190539e-01 -2.47645863e-01 -2.47636795e-01
 -2.47020695e-01 -2.47009318e-01 -2.46322049e-01 -2.46308149e-01
 -2.45549945e-01 -2.45533332e-01 -2.44704404e-01 -2.44684920e-01
 -2.43785450e-01 -2.43762969e-01 -2.42793104e-01 -2.42767545e-01
 -2.41727389e-01 -2.41698720e-01 -2.40588326e-01 -2.40556574e-01
 -2.39375936e-01 -2.39341193e-01 -2.38090237e-01 -2.38052673e-01
 -2.36731249e-01 -2.36691118e-01 -2.35298988e-01 -2.35256640e-01
 -2.33793469e-01 -2.33749359e-01 -2.32214705e-01 -2.32169405e-01
 -2.30562709e-01 -2.30516913e-01 -2.28837492e-01 -2.28792028e-01
 -2.27039068e-01 -2.26994900e-01 -2.25167448e-01 -2.25125685e-01
 -2.23222649e-01 -2.23184544e-01 -2.21204689e-01 -2.21171640e-01
 -2.19113594e-01 -2.19087138e-01 -2.16949396

# 고유치 계산
## 밴드 행렬
### Symmetric / Hermitian 밴드 행렬의 고유치와 고유벡터
- linalg.eig_banded
    - Lapack: sbevd, hbevd 
- eigvals, eigvecs = linalg.eig_banded(band_a_h, lower=False)
- band_a_h = read_banded_h("inp_band.txt", ubw, dtype=np.float64, delimiter=",", lower=False)
### Symmetric / Hermitian 밴드 행렬의 고유치만 구하기
- eigvals = linalg.eig_banded(bnad_a_h, lower=False, eigvals_only = True)

In [7]:
A = np.array([[1,5,2,0], [5,2,5,2], [2,5,3,5], [0,2,5,4]])
A_band_h = np.array([[0,0,2,2], [0,5,5,5], [1,2,3,4]])  # upper form
eigvals, eigvecs = linalg.eig_banded(A_band_h, lower=False)
print("eigenvalue: ", eigvals, "eigvectors: ", eigvecs)

eigenvalue:  [-4.26200532 -2.22987175  3.95222349 12.53965359] eigvectors:  [[ 0.54585106 -0.49026342 -0.58943537  0.33801529]
 [-0.73403852  0.04827646 -0.41123929  0.53827417]
 [ 0.39896071  0.67105283  0.15802574  0.60460427]
 [-0.06375287 -0.55407514  0.6771086   0.48006276]]


In [15]:
# Construct  Matrix A
diag_vec = 3 * np.ones((1000,))
first_band = -1 * np.ones((999,))
minus_band = -1 * np.ones((999,))
A = np.diag(diag_vec) + np.diag(first_band, k=1) + np.diag(minus_band, k=-1)

# Construct Band Matrix of A
zr = np.zeros((1,))
minus_one_vec = np.ones((999,))
first_row_band_matrix = np.hstack((zr, minus_one_vec))

band_A = np.vstack((first_row_band_matrix, diag_vec))

# Check computing time for eigenvalue, eigenvector of full A
start = timeit.default_timer()
eigvals, eigvecs = linalg.eig(A)
end = timeit.default_timer()
print("computing time: ", end - start)

computing time:  0.6021723349695094


In [16]:
# Check computing time for eigenvalue, eigenvector of band A
start = timeit.default_timer()
eigvals, eigvecs = linalg.eig_banded(band_A, lower=False)
end = timeit.default_timer()
print("computing time: ", end - start)

computing time:  0.05713733902666718


In [20]:
# Check computing time for eigenvalue, eigenvector of full A
start = timeit.default_timer()
eigvals, eigvecs = linalg.eigh(A)
end = timeit.default_timer()
print("computing time: ", end - start)


computing time:  0.10907496797153726


#### band_A를 입력으로 받아 eig_banded()를 사용한 방법이 가장 빠르다.

# Power Method 개론
: eigenvalues에서 가장 큰 eigenvalue를 구하는 방법

## Power method
$Av = \lambda v$, n x n $|{\lambda}_1| > |{\lambda}_2| \ge |{\lambda}_3| \ge \dots \ge |{\lambda}_n|$
- ${\lambda}_1$은 중복되지 않고, 각 eigenvalue들은 independent하다. $\to$ A is diagonalizable
- ${x}_0$ 를 nonzero라고 가정, 
    - ${x}_0 = {c}_1{v}_1  + \dots + {c}_n{v}_n$ 
    - ${x}_1 = A{x}_0$
    - ${x}_2 = A{x}_1$
    - $\vdots$
    - ${x}_k = A{x}_{k-1} = {A}^k{x}_0$
    - $k \to \infty, \frac{1}{({\lambda}_1)}^k{A}^k{x}_0 = {c}_1{v}_1$
    
- ${\lambda}_1 = \frac{{x}_k^TA{x}_k}{{x}_k^T{x}_k} = \frac{{x}_k\cdot(A{x}_k)}{{x}_k\cdot{x}_k}$ : **the largest eigenvalue**
- $\|{x}_k\|$ can grow too much! $\to$ Normalize to a unit vector (${x}_1 = \frac{A{x}_0}{\|A{x}_0\|} \dots {x}_k = \frac{A{x}_k}{\|A{x}_k\|}$)

### 알고리즘
- 1. 초기벡터 ${x}_0$ 선택(norm=1)
- 2. 반복계산 k=1, 2, $\dots$:
    - a. ${x}_k =  A{x}_{k-1}/\|A{x}_{k-1}\|$
    - b. ${\mu}_k = {x}_{k} \dots (A{x}_k) / {x}_k \dots {x}_k$
    - 에러가 충분히 작으면 종료
- ${\mu}_k \approx$ the largest eigenvalue
- ${x}_k \approx$ corresponding eigenvector (norm=1)

- eigenvector relative error = $\|{x}_k - {x}_{k-1}\| / \|{x}_k\|$
- eigenvalue relative error = $|{\mu}_k - {\mu}_{k-1}| / |{\mu}_k|$

## Inverse Power Method
$Av = \lambda v$ $\Longleftrightarrow$ ${A}^{-1}v = \frac{1}{\lambda}v$
- $|{\lambda}_1| > |{\lambda}_2| \ge |{\lambda}_3| \ge \dots \ge |{\lambda}_n| > 0$  
- $|{{\lambda}_{n}^{-1}}| > |{{\lambda}_{n-1}^{-1}}| \ge \dots \ge |{{\lambda}_{1}^{-1}}| > 0$
- Power method 알고리즘을 그대로 사용하여 the smallest eigenvalue를 구할 수 있다.
- Power method:
    - ${x}_k = \frac{A{x}_{k-1}}{\|A{x}_{k-1}\|}$
    - ${\mu}_k = \frac{{x}_{k}\cdot(A{x}_k)}{{x}_{k}\cdot{x}_k} \approx {\lambda}_1$

- Inverse Power method:
    - ${x}_k = \frac{A^{-1}{x}_{k-1}}{\|A^{-1}{x}_{k-1}\|}$
    - ${\mu}_k = \frac{{x}_{k}\cdot({A}^{-1}{x}_k)}{{x}_{k}\cdot{x}_k} \approx \frac{1}{{\lambda}_{1}}$
    - solve: $A{x}_{k+1} = {x}_k$