In [1]:
from tqdm.auto import tqdm
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist

# load data
(x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, one_hot_label=True)
network = NeuralNetMLP(input_size=784, hidden_size=256, output_size=10)

iters_num = 100
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.001

train_loss_list = []
train_acc_list = []
test_acc_list = []

iter_per_epoch = max(train_size / batch_size, 1)

for i in tqdm(range(iters_num)):
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]
    
    # 오차역전파법으로 기울기를 구한다.
    grad = network.gradient(x_batch, t_batch)
    
    # 갱신
    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]
        
    loss = network.loss(x_batch, t_batch)
    
    train_loss_list.append(loss)
    
    if i % iter_per_epoch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        train_acc_list.append(train_acc)
        test_acc_list.append(test_acc)
        print(loss, train_acc, test_acc)

NameError: name 'NeuralNetMLP' is not defined

In [14]:
import numpy as np

def softmax(x):
    if x.ndim == 2:
        print("exe if statement")
        x = x.T
        x = x - np.max(x, axis=0)
        y = np.exp(x) / np.sum(np.exp(x), axis=0)
        return y.T 
    print("just softmax")
    x = x - np.max(x) # 오버플로 대책
    return np.exp(x) / np.sum(np.exp(x))

In [18]:
x = np.array([[1,2], [3,4], [5,6]])
print(x)
print()
print(x.T)

a = np.max(x, axis=0)
print()
print(a)
print()
print(x-a)

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]

[5 6]

[[-4 -4]
 [-2 -2]
 [ 0  0]]


In [19]:
x1 = np.array([[1,2], [3,4], [5,6]])
x2 = np.array([1,2])

In [23]:
x3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(x3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    # 훈련 데이터가 원-핫 벡터라면 정답 레이블의 인덱스로 반환
    if t.size == y.size:
        t = t.argmax(axis=1)
             
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size