In [2]:
# AND function

def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1 * w1 + x2 * w2
    if tmp <= theta:
        return 0
    else:
        return 1

In [3]:
# numpy 구현
import numpy as np

x = np.array([0,1])  # 입력
w = np.array([0.5, 0.5])  # weight
b = -0.7  # bias

sum(w * x) + b

-0.19999999999999996

In [4]:
# weight, bias 도입한 AND 게이트

def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.7
    tmp = np.sum(w * x) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [5]:
# NAND & OR Gate

def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-0.5, -0.5])
    b = 0.7
    tmp = np.sum(x * w) + b
    if tmp <= 0:
        return 0
    else:
        return 1
    

def OR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([0.5, 0.5])
    b = -0.2
    tmp = np.sum(x * w) + b
    if tmp <= 0:
        return 0
    else:
        return 1

In [6]:
# XOR Gate 구현

def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    return y

In [7]:
XOR(0, 0)

0

In [39]:
X = np.array([0, 1, 0, 1, 0, 0, 1, 1]).reshape(2,4)
Y = np.array([0, 1, 1, 0])
X, Y

(array([[0, 1, 0, 1],
        [0, 0, 1, 1]]),
 array([0, 1, 1, 0]))

In [40]:
def init_parameters(num_hidden=2):
    W1 = np.zeros((2, num_hidden))
    B1 = np.zeros((num_hidden, 1))
    W2 = np.zeros((2, num_hidden))
    B2 = np.zeros((num_hidden, 1))
    return W1, B1, W2, B2

W1, B1, W2, B2 = init_parameters()

In [41]:
W1, B1, W2, B2

(array([[0., 0.],
        [0., 0.]]),
 array([[0.],
        [0.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[0.],
        [0.]]))

In [42]:
def dot(W, X, B):
    return np.dot(W.T, X) + B

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [43]:
Z1 = dot(W1, X, B1)
H = sigmoid(Z1)

In [44]:
Z2 = dot(W2, X, B2)
Y_hat = sigmoid(Z2)

In [47]:
def loss_eval(_params):
    W1, B1, W2, B2 = _params
    
    # Forward: Input Layer
    Z1 = dot(W1, X, B1)
    H = sigmoid(Z1)
    
    # Forward: Hidden Layer
    Z2 = dot(W2, X, B2)
    Y_hat = sigmoid(Z2)
    
    loss = 1./X.shape[1] * np.sum(-1 * (Y * np.log(Y_hat) + (1-Y) * np.log(1-Y_hat)))
    return Z1, H, Z2, Y_hat, loss

In [48]:
loss_eval([W1, B1, W2, B2])[-1]

1.3862943611198906